#pw=str(input("Enter password :"))
#print("#pass is :",hash(pw))
unm=str(input("enter the username:"))
pw=str(input("Enter the password"))
a=hash(pw)
print('Username:',unm)
print("Hash pass is :",hash(pw))
f=open("pwd.txt","w+")
f.write("%s"%(unm))
f.write("%s"%(a))
f.close()