name=str(input("Enter your name: "))
pw=str(input("Enter password: "))
a=hash(pw)
print("Username: ",name)
print("Hash value of password is :",a)
f=open("user.txt","w+")
f.write("%s"%(name))
f.write("%s"%(a))
f.close()
